# Generated by Django 4.2.4 on 2023-08-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
